jQuery(function wms_mt_stores() {
    var columns1 = $('#store_table').columns({
        data: [
            { 'order_channel_id': '012', 'store_name': 'BCSH', 'store_comment': 'BCBG上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '012', 'store_name': 'BCLA', 'store_comment': 'BCBG洛杉矶仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '012', 'store_name': 'CH', 'store_comment': 'BCBG超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '006', 'store_name': 'BHSH', 'store_comment': 'BHFO上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '006', 'store_name': 'BH', 'store_comment': 'BHFO品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '006', 'store_name': 'BHHB', 'store_comment': 'BHFO哈尔滨退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '006', 'store_name': 'BHLA', 'store_comment': 'BHFO洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '006', 'store_name': 'CH', 'store_comment': 'BHFO超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '007', 'store_name': 'CPSH', 'store_comment': 'CP上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '007', 'store_name': 'CH', 'store_comment': 'CP超卖仓库', 'store_area': 'HK', 'is_sale': '0' },
            { 'order_channel_id': '007', 'store_name': 'CP', 'store_comment': 'CP香港仓库', 'store_area': 'HK', 'is_sale': '1' },
            { 'order_channel_id': '015', 'store_name': 'GT-SH', 'store_comment': 'GILT上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '015', 'store_name': 'GT', 'store_comment': 'GILT品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '015', 'store_name': 'GT-LA', 'store_comment': 'GILT洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '015', 'store_name': 'CH', 'store_comment': 'GILT超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCSH-OS', 'store_comment': 'JC上海退货仓库(OneStop)', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCSH-WB', 'store_comment': 'JC上海退货仓库(WB)', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JC', 'store_comment': 'JC品牌方仓库（库存由香港管理，此仓库已不作为销售仓库）', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCHB-WB', 'store_comment': 'JC哈尔滨WB退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCHB', 'store_comment': 'JC哈尔滨退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCLA', 'store_comment': 'JC洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '013', 'store_name': 'SELA', 'store_comment': 'JC洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'CH', 'store_comment': 'JC超卖仓库', 'store_area': 'HK', 'is_sale': '0' },
            { 'order_channel_id': '004', 'store_name': 'JCHK', 'store_comment': 'JC香港仓库', 'store_area': 'HK', 'is_sale': '1' },
            { 'order_channel_id': '010', 'store_name': 'JWOF', 'store_comment': 'JW上海办公室退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '010', 'store_name': 'JWSH', 'store_comment': 'JW上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '010', 'store_name': 'JW', 'store_comment': 'JW品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '010', 'store_name': 'JWLA', 'store_comment': 'JW洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '010', 'store_name': 'CH', 'store_comment': 'JW超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '017', 'store_name': 'LV-SH', 'store_comment': 'Lucky Vitamin上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '017', 'store_name': 'LV', 'store_comment': 'Lucky Vitamin品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '017', 'store_name': 'LV-LA', 'store_comment': 'Lucky Vitamin洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '017', 'store_name': 'CH', 'store_comment': 'Lucky Vitamin超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '002', 'store_name': 'PA', 'store_comment': 'PA美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '002', 'store_name': 'CH', 'store_comment': 'PA超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '013', 'store_name': 'SESH', 'store_comment': 'Sears上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '013', 'store_name': 'SE', 'store_comment': 'Sears品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '013', 'store_name': 'SECHI', 'store_comment': 'Sears芝加哥退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '013', 'store_name': 'CH', 'store_comment': 'Sears超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '016', 'store_name': 'SC-SH', 'store_comment': 'ShoeCity上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '016', 'store_name': 'SC', 'store_comment': 'ShoeCity品牌方仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '016', 'store_name': 'SC-LA', 'store_comment': 'ShoeCity洛杉矶退货仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '016', 'store_name': 'CH', 'store_comment': 'ShoeCity超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '001', 'store_name': 'TM', 'store_comment': 'SN上海仓库', 'store_area': 'CN', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'WHS', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'SL', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'IK', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'IKN', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'KSS', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'PRV', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'MMM', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'BAK', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'TST', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'SPD', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'ASC', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'DP', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'SG1', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'SG2', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'SG3', 'store_comment': 'SN美国仓库', 'store_area': 'US', 'is_sale': '1' },
            { 'order_channel_id': '001', 'store_name': 'CH', 'store_comment': 'SN超卖仓库', 'store_area': 'US', 'is_sale': '0' },
            { 'order_channel_id': '005', 'store_name': 'SP', 'store_comment': 'SP上海仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '005', 'store_name': 'SPLY', 'store_comment': 'SP临沂仓库', 'store_area': 'CN', 'is_sale': '1' },
            { 'order_channel_id': '005', 'store_name': 'CH', 'store_comment': 'SP超卖仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '014', 'store_name': 'WMFSH', 'store_comment': 'WMF上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '014', 'store_name': 'WMF', 'store_comment': 'WMF品牌方仓库', 'store_area': 'GER', 'is_sale': '1' },
            { 'order_channel_id': '014', 'store_name': 'WMFHB', 'store_comment': 'WMF哈尔滨退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '014', 'store_name': 'CH', 'store_comment': 'WMF超卖仓库', 'store_area': 'GER', 'is_sale': '0' },
            { 'order_channel_id': '008', 'store_name': 'RMSH', 'store_comment': '皇马上海退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '008', 'store_name': 'RM', 'store_comment': '皇马品牌方仓库', 'store_area': 'UK', 'is_sale': '1' },
            { 'order_channel_id': '008', 'store_name': 'RMHB', 'store_comment': '皇马哈尔滨退货仓库', 'store_area': 'CN', 'is_sale': '0' },
            { 'order_channel_id': '008', 'store_name': 'CH', 'store_comment': '皇马超卖仓库', 'store_area': 'UK', 'is_sale': '0' }
        ]
    });
})